::sa::_backgroundSaeShell::signalProcessReady 1776165181
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 testbenchName default resultsDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/results testSuiteDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric databaseName /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 testbenchName default resultsDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/results testSuiteDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric databaseName /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::parentRunning
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 testbenchName default resultsDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/results testSuiteDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric databaseName /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 testbenchName default resultsDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/results testSuiteDir /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric databaseName /home/itsupport/simulation/inverter,tb_pmos,schematic/history_1/simulation/default/HSPICE/parametric/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::parentRunning
::wf::viewerExited
