::sa::_backgroundSaeShell::signalProcessReady 1779538352
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/parametric/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_d_Fff resultsDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/parametric/results testSuiteDir /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/parametric databaseName /home/itsupport/simulation/project_d_ff,D_FF_tb,schematic/history_1/simulation/HSPICE_d_Fff/HSPICE/parametric/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::exit
